03 - CarRental Website/Controllers/VehicleController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace DoggyStyle.Controllers
{
    [Authorize(Roles = "Admin")]
    public class VehicleController : Controller
    {
        private DoggyStyleEntities db = new DoggyStyleEntities();

        //
        // GET: /Vehicle/

        public ActionResult Index()
        {
            var vehicles = db.Vehicles.Include(v => v.Manufactor).OrderBy(v => v.Manufactor.Name).OrderBy(v => v.Model);
            return View(vehicles.ToList());
        }

        //
        // GET: /Vehicle/Details/5

        //public ActionResult Details(int id = 0)
        //{
        //    Vehicle vehicle = db.Vehicles.Find(id);
        //    if (vehicle == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(vehicle);
        //}

        //
        // GET: /Vehicle/Create

        public ActionResult Create()
        {
            ViewBag.ManufactorId = new SelectList(db.Manufactors, "ManufactorId", "Name");
            ViewBag.ErrorMessage = "";
            return View();
        }

        //
        // POST: /Vehicle/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Vehicle vehicle)
        {
            int VehicleId = 0;
            using (RentalsLogic logic = new RentalsLogic())
            {
                VehicleId = logic.IsVehicleExsist(vehicle.ManufactorId, vehicle.Model, vehicle.Year, vehicle.Transmission);
            }

            if (VehicleId > 0)
            {
                ViewBag.ErrorMessage = "This type of Vehicle already exsist.";
                ViewBag.ManufactorId = new SelectList(db.Manufactors, "ManufactorId", "Name", vehicle.ManufactorId);
                return View(vehicle);
            }

            if (ModelState.IsValid)
            {
                db.Vehicles.Add(vehicle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ManufactorId = new SelectList(db.Manufactors, "ManufactorId", "Name", vehicle.ManufactorId);
            return View(vehicle);
        }

        //
        // GET: /Vehicle/Edit/5

        public ActionResult Edit(int id = 0)
        {
            ViewBag.ErrorMessage = "";
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            ViewBag.ManufactorId = new SelectList(db.Manufactors, "ManufactorId", "Name", vehicle.ManufactorId);
            return View(vehicle);
        }

        //
        // POST: /Vehicle/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                int VehicleId = 0;
                using (RentalsLogic logic = new RentalsLogic())
                {
                    VehicleId = logic.IsVehicleExsist(vehicle.ManufactorId, vehicle.Model, vehicle.Year, vehicle.Transmission);
                }

                if (VehicleId != 0 && VehicleId != vehicle.TypeId)
                {
                    ViewBag.ErrorMessage = "This type of Vehicle already exsist.";
                    ViewBag.ManufactorId = new SelectList(db.Manufactors, "ManufactorId", "Name", vehicle.ManufactorId);
                    return View(vehicle);
                }

                db.Entry(vehicle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ManufactorId = new SelectList(db.Manufactors, "ManufactorId", "Name", vehicle.ManufactorId);
            return View(vehicle);
        }

        //
        // GET: /Vehicle/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        //
        // POST: /Vehicle/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vehicle vehicle = db.Vehicles.Find(id);
            db.Vehicles.Remove(vehicle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

03 - CarRental Website/Views/Vehicle/Create.cshtml
@model DoggyStyle.Vehicle

@{
    ViewBag.Title = "Create Vehicle";
}

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div style="width: 45%; margin-left: auto; margin-right: auto;">
        <fieldset style="width: 100%;">
            <legend>@ViewBag.Title</legend>
            <div style="width: 60%; float: left;">
                <table>
                    <tr>
                        <td>
                            @Html.LabelFor(model => model.ManufactorId, "Manufactor")
                        </td>
                        <td>&nbsp;&nbsp;</td>
                        <td>
                            @Html.DropDownList("ManufactorId", String.Empty)
                            @Html.ValidationMessageFor(model => model.ManufactorId)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(model => model.Model)
                        </td>
                        <td>&nbsp;&nbsp;</td>
                        <td>
                            @Html.EditorFor(model => model.Model, new { @class = "sg-input sg-input-text" })
                            @Html.ValidationMessageFor(model => model.Model)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(model => model.Year)
                        </td>
                        <td>&nbsp;&nbsp;</td>
                        <td>
                            @Html.EditorFor(model => model.Year)
                            @Html.ValidationMessageFor(model => model.Year)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(model => model.Transmission)
                        </td>
                        <td>&nbsp;&nbsp;</td>
                        <td>
                            @Html.EditorFor(model => model.Transmission)
                            @Html.ValidationMessageFor(model => model.Transmission)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(model => model.DailyRentalRate)
                        </td>
                        <td>&nbsp;&nbsp;</td>
                        <td>
                            @Html.EditorFor(model => model.DailyRentalRate)
                            @Html.ValidationMessageFor(model => model.DailyRentalRate)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(model => model.PenaltyDailyRate)
                        </td>
                        <td>&nbsp;&nbsp;</td>
                        <td>
                            @Html.EditorFor(model => model.PenaltyDailyRate)
                            @Html.ValidationMessageFor(model => model.PenaltyDailyRate)
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;&nbsp;</td>
                    </tr>
                    <tr>
                        <td>
                            <input type="submit" class="btn btn-primary btn-lg specs-link" value="Create New" />
                            @*@Html.HiddenFor(model => model.TypeId)*@
                        </td>
                        <td>&nbsp;&nbsp;</td>
                        @if (ViewBag.ErrorMessage != "")
                        {
                            <td class="error">@ViewBag.ErrorMessage</td>
                        }
                        else {
                            <td>@Html.ActionLink("Back to Vehicles List", "Index")</td>
                        }
                    </tr>
                </table>
            </div>
        </fieldset>
    </div>

}

<style>
    body {
        margin-left: auto;
        margin-right: auto;
    }

    tr {
        height: 3em;
    }

    .sg-input-text {
        padding: .2em .3em;
        border-radius: .3em;
    }
    .error {
        font-weight: bold;
        color: red;
    }
</style>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

03 - CarRental Website/Views/Vehicle/Delete.cshtml
@model DoggyStyle.Vehicle

@{
    ViewBag.Title = "Delete Vehicle";
}

<div style="width: 45%; margin-left: auto; margin-right: auto;">
    <fieldset style="width: 100%;">
        <legend>@ViewBag.Title</legend>
        <div style="width: 60%; float: left;">
            <table>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.Manufactor.Name)
                    </td>
                    <td>&nbsp;&nbsp;</td>
                    <td>
                        @Html.DisplayFor(model => model.Manufactor.Name)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.Model)
                    </td>
                    <td>&nbsp;&nbsp;</td>
                    <td>
                        @Html.DisplayFor(model => model.Model, new { @class = "sg-input sg-input-text" })
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.Year)
                    </td>
                    <td>&nbsp;&nbsp;</td>
                    <td>
                        @Html.DisplayFor(model => model.Year)
                    </td>
                </tr>
                <tr>
                    <td style="font-weight: bold;">Automatic Transmission
                    </td>
                    <td>&nbsp;&nbsp;</td>
                    <td>
                        @Html.DisplayFor(model => model.Transmission)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.DailyRentalRate)
                    </td>
                    <td>&nbsp;&nbsp;</td>
                    <td>
                        @Html.DisplayFor(model => model.DailyRentalRate)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.PenaltyDailyRate)
                    </td>
                    <td>&nbsp;&nbsp;</td>
                    <td>
                        @Html.DisplayFor(model => model.PenaltyDailyRate)
                    </td>
                </tr>
            </table>
        </div>
    </fieldset>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div style="width: 45%; margin-left: auto; margin-right: auto;">

        <div style="width: 60%; float: left;">
            <table>
                <tr>
                    <td>&nbsp;&nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <input type="submit" class="btn btn-primary btn-lg specs-link" value="Confirm Delete" />
                        @Html.HiddenFor(model => model.TypeId)
                    </td>
                    <td>&nbsp;&nbsp;</td>
                    <td>@Html.ActionLink("Back to Vehicles List", "Index")</td>
                </tr>
            </table>
        </div>

    </div>
}

<style>
    body {
        margin-left: auto;
        margin-right: auto;
    }

    tr {
        height: 3em;
    }

    .sg-input-text {
        padding: .2em .3em;
        border-radius: .3em;
    }
</style>

03 - CarRental Website/Views/Vehicle/Edit.cshtml
@model DoggyStyle.Vehicle

@{
    ViewBag.Title = "Type of Vehicle";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div style="width: 45%; margin-left: auto; margin-right: auto;">
        <fieldset style="width: 100%;">
            <legend>@ViewBag.Title</legend>
            <div style="width: 60%; float: left;">
                <table>
                    <tr>
                        <td>
                            @Html.LabelFor(model => model.Manufactor)
                        </td>
                        <td>&nbsp;&nbsp;</td>
                        <td>
                            @Html.DropDownList("ManufactorId", String.Empty)
                            @Html.ValidationMessageFor(model => model.ManufactorId)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(model => model.Model)
                        </td>
                        <td>&nbsp;&nbsp;</td>
                        <td>
                            @Html.EditorFor(model => model.Model, new { @class = "sg-input sg-input-text" })
                            @Html.ValidationMessageFor(model => model.Model)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(model => model.Year)
                        </td>
                        <td>&nbsp;&nbsp;</td>
                        <td>
                            @Html.EditorFor(model => model.Year)
                            @Html.ValidationMessageFor(model => model.Year)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(model => model.Transmission)
                        </td>
                        <td>&nbsp;&nbsp;</td>
                        <td>
                            @Html.EditorFor(model => model.Transmission)
                            @Html.ValidationMessageFor(model => model.Transmission)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(model => model.DailyRentalRate)
                        </td>
                        <td>&nbsp;&nbsp;</td>
                        <td>
                            @Html.EditorFor(model => model.DailyRentalRate)
                            @Html.ValidationMessageFor(model => model.DailyRentalRate)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(model => model.PenaltyDailyRate)
                        </td>
                        <td>&nbsp;&nbsp;</td>
                        <td>
                            @Html.EditorFor(model => model.PenaltyDailyRate)
                            @Html.ValidationMessageFor(model => model.PenaltyDailyRate)
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;&nbsp;</td>
                    </tr>
                    <tr>
                        <td>
                            <input type="submit" class="btn btn-primary btn-lg specs-link" value="Update" />
                            @Html.HiddenFor(model => model.TypeId)
                        </td>
                        <td>&nbsp;&nbsp;</td>
                        @if (ViewBag.ErrorMessage != "")
                        {
                            <td class="error">@ViewBag.ErrorMessage</td>
                        }
                        else {
                            <td>@Html.ActionLink("Back to Vehicles List", "Index")</td>
                        }
                    </tr>
                </table>
            </div>
        </fieldset>
    </div>
}

<style>
    body {
        margin-left: auto;
        margin-right: auto;
    }

    tr {
        height: 3em;
    }

    .sg-input-text {
        padding: .2em .3em;
        border-radius: .3em;
    }
    .error {
        font-weight: bold;
        color: red;
    }
</style>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
    $(function () {
        $("#btnSubmit").on('click', function (e) {
            debugger;
            //validate date format

            //document.getElementById('UserName').value = document.getElementById('formLogin').value;
            //document.getElementById('Password').value = document.getElementById('formPass').value;
            //document.getElementById('RememberMe').checked = document.getElementById('formRememberMe').checked;
            //document.getElementById('submit').click();

        });
    });
</script>
}

03 - CarRental Website/Views/Vehicle/Index.cshtml
@model IEnumerable<DoggyStyle.Vehicle>

@{
    ViewBag.Title = "Vehicles";
}

<div>
    <div style="float: left;">
        <h3>@ViewBag.Title</h3>
    </div>
    <div style="float: right; padding-top: 1.5em; padding-right: 1em;">
        <img src="~/Content/images/icons/search.png" width="24" />
        &nbsp;&nbsp;&nbsp;&nbsp;
        <input id="searchFilter" class="searchFilter" onkeyup="searchFilter(this.value, 'tblVehicles', 6)" />
    </div>
    <table style="width: 100%;">
        <tr>
            <td>
                <p>
                    <a href='@Url.Action("Create", "Vehicle")'>
                        <img src='@Url.Content("~/Content/images/icons/addItem.png")' title='Add new Vehicle'/>
                    </a>
                </p>
            </td>
        </tr>
    </table>
</div>
<br />

<table id="tblVehicles" class="responstable">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.TypeId)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Manufactor.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Year)
        </th>
        <th>Automatic Trasmission
            @*@Html.DisplayNameFor(model => model.Transmission)*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DailyRentalRate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PenaltyDailyRate)
        </th>
        <th>Actions</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
            @Html.DisplayFor(modelItem => item.TypeId)
        </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Manufactor.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td style="width: 60px;">
                @Html.DisplayFor(modelItem => item.Transmission)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DailyRentalRate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PenaltyDailyRate)
            </td>
            <td>
                <a href='@Url.Action("Edit", "Vehicle", new { id = item.TypeId })'>
                    <img src='@Url.Content("~/Content/images/icons/editItem.png")' title='Modify Vehicle @item.Manufactor.Name @item.Model @item.Year'/>
                </a>
                &nbsp;&nbsp;&nbsp;
            @*<a href='#' style="cursor: default;">
                <img src='@Url.Content("~/Content/images/icons/deleteItem.png")' title='Current Vehicle cannot be deleted. Fleet attached.' style="opacity: 0.2;"/> 
            </a>*@
                @{
        using (DoggyStyle.RentalsLogic logic = new DoggyStyle.RentalsLogic())
        {
            if (!logic.IsVehicleOccupied(item.TypeId))
            { 
                    <a href='@Url.Action("Delete", "Vehicle", new { id = item.TypeId })'>
                        <img src='@Url.Content("~/Content/images/icons/deleteItem.png")' title='Remove Vehicle @item.Manufactor.Name @item.Model @item.Year'/>
                    </a>
            }
            else
            { 
                    <a href='#' style="cursor: default;">
                        <img src='@Url.Content("~/Content/images/icons/deleteItem.png")' title='Current Vehicle cannot be deleted. Fleet attached.' style="opacity: 0.2;"/>
                    </a>
            }
        }
                }

                @*@Html.ActionLink("Edit", "Edit", new { id=item.TypeId  }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
            </td>
        </tr>
    }

</table>

<style>
    body {
        margin: 1em;
    }
</style>